module.exports = `
{
    "name": "${appName}",
    "version": "0.0.1",
    "description": "${appName} generated by floodesh",
    "main": "index.js",
    "scripts": {
        "test": "./node_modules/mocha/bin/mocha --reporter spec --bail --timeout 10000 test/test-spider.js"
    },
    "keywords": [
    "${appName}",
    "floodesh",
    "spider",
    "crawler",
    "web"
    ],
    "dependencies":{
        "floodesh":"^0.2.12",
        "mof-cheerio":"^1.0.4",
	"moment":"^2.12.0"
    },
    "devDependencies":{
        "mocha": "^2.4.5",
        "should": "^8.2.1",
        "should-sinon": "^0.0.5",
        "sinon": "^1.17.3"
    }
}
`